// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: AlgoCenter.proto

package GateWayProtos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlgoCenterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId   string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`       // 请求唯一标识
	UserId      int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // 用户ID
	ExpList     []int32  `protobuf:"varint,3,rep,packed,name=exp_list,json=expList,proto3" json:"exp_list,omitempty"`     // 实验Id列表
	RetCount    int32    `protobuf:"varint,4,opt,name=ret_count,json=retCount,proto3" json:"ret_count,omitempty"`         // 物料返回数量
	LlId        int64    `protobuf:"varint,5,opt,name=ll_id,json=llId,proto3" json:"ll_id,omitempty"`                     // 物料ID
	ResType     int32    `protobuf:"varint,6,opt,name=res_type,json=resType,proto3" json:"res_type,omitempty"`            // 物料类目
	ResName     string   `protobuf:"bytes,7,opt,name=res_name,json=resName,proto3" json:"res_name,omitempty"`             // 物料名称
	KeynameList []string `protobuf:"bytes,8,rep,name=keyname_list,json=keynameList,proto3" json:"keyname_list,omitempty"` // 物料关键词列表
}

func (x *AlgoCenterRequest) Reset() {
	*x = AlgoCenterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AlgoCenter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlgoCenterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgoCenterRequest) ProtoMessage() {}

func (x *AlgoCenterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AlgoCenter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgoCenterRequest.ProtoReflect.Descriptor instead.
func (*AlgoCenterRequest) Descriptor() ([]byte, []int) {
	return file_AlgoCenter_proto_rawDescGZIP(), []int{0}
}

func (x *AlgoCenterRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AlgoCenterRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AlgoCenterRequest) GetExpList() []int32 {
	if x != nil {
		return x.ExpList
	}
	return nil
}

func (x *AlgoCenterRequest) GetRetCount() int32 {
	if x != nil {
		return x.RetCount
	}
	return 0
}

func (x *AlgoCenterRequest) GetLlId() int64 {
	if x != nil {
		return x.LlId
	}
	return 0
}

func (x *AlgoCenterRequest) GetResType() int32 {
	if x != nil {
		return x.ResType
	}
	return 0
}

func (x *AlgoCenterRequest) GetResName() string {
	if x != nil {
		return x.ResName
	}
	return ""
}

func (x *AlgoCenterRequest) GetKeynameList() []string {
	if x != nil {
		return x.KeynameList
	}
	return nil
}

type ItemData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LlId    int64 `protobuf:"varint,1,opt,name=ll_id,json=llId,proto3" json:"ll_id,omitempty"`          // 物料ID
	ResType int64 `protobuf:"varint,2,opt,name=res_type,json=resType,proto3" json:"res_type,omitempty"` // 物料类目
	Source  int32 `protobuf:"varint,3,opt,name=source,proto3" json:"source,omitempty"`                  // 推荐召回id
}

func (x *ItemData) Reset() {
	*x = ItemData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AlgoCenter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemData) ProtoMessage() {}

func (x *ItemData) ProtoReflect() protoreflect.Message {
	mi := &file_AlgoCenter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemData.ProtoReflect.Descriptor instead.
func (*ItemData) Descriptor() ([]byte, []int) {
	return file_AlgoCenter_proto_rawDescGZIP(), []int{1}
}

func (x *ItemData) GetLlId() int64 {
	if x != nil {
		return x.LlId
	}
	return 0
}

func (x *ItemData) GetResType() int64 {
	if x != nil {
		return x.ResType
	}
	return 0
}

func (x *ItemData) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

type AlgoCenterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64       `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`      // 用户ID
	ItemList []*ItemData `protobuf:"bytes,2,rep,name=item_list,json=itemList,proto3" json:"item_list,omitempty"` // 推荐物料列表
}

func (x *AlgoCenterResponse) Reset() {
	*x = AlgoCenterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AlgoCenter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlgoCenterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgoCenterResponse) ProtoMessage() {}

func (x *AlgoCenterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AlgoCenter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgoCenterResponse.ProtoReflect.Descriptor instead.
func (*AlgoCenterResponse) Descriptor() ([]byte, []int) {
	return file_AlgoCenter_proto_rawDescGZIP(), []int{2}
}

func (x *AlgoCenterResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AlgoCenterResponse) GetItemList() []*ItemData {
	if x != nil {
		return x.ItemList
	}
	return nil
}

var File_AlgoCenter_proto protoreflect.FileDescriptor

var file_AlgoCenter_proto_rawDesc = []byte{
	0x0a, 0x10, 0x41, 0x6c, 0x67, 0x6f, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0f, 0x43, 0x4f, 0x4d, 0x4d, 0x5f, 0x41, 0x6c, 0x67, 0x6f, 0x43, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x22, 0xf1, 0x01, 0x0a, 0x11, 0x41, 0x6c, 0x67, 0x6f, 0x43, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x07, 0x65, 0x78, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x72, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x6c, 0x6c, 0x5f,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x72, 0x65, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x73,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6b, 0x65, 0x79, 0x6e, 0x61, 0x6d, 0x65, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x6b, 0x65, 0x79, 0x6e,
	0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x52, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x13, 0x0a, 0x05, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x73, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x65, 0x0a, 0x12, 0x41,
	0x6c, 0x67, 0x6f, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x36, 0x0a, 0x09, 0x69, 0x74,
	0x65, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x43, 0x4f, 0x4d, 0x4d, 0x5f, 0x41, 0x6c, 0x67, 0x6f, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4c, 0x69,
	0x73, 0x74, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x3b, 0x47, 0x61, 0x74, 0x65, 0x57, 0x61, 0x79,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_AlgoCenter_proto_rawDescOnce sync.Once
	file_AlgoCenter_proto_rawDescData = file_AlgoCenter_proto_rawDesc
)

func file_AlgoCenter_proto_rawDescGZIP() []byte {
	file_AlgoCenter_proto_rawDescOnce.Do(func() {
		file_AlgoCenter_proto_rawDescData = protoimpl.X.CompressGZIP(file_AlgoCenter_proto_rawDescData)
	})
	return file_AlgoCenter_proto_rawDescData
}

var file_AlgoCenter_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_AlgoCenter_proto_goTypes = []interface{}{
	(*AlgoCenterRequest)(nil),  // 0: COMM_AlgoCenter.AlgoCenterRequest
	(*ItemData)(nil),           // 1: COMM_AlgoCenter.ItemData
	(*AlgoCenterResponse)(nil), // 2: COMM_AlgoCenter.AlgoCenterResponse
}
var file_AlgoCenter_proto_depIdxs = []int32{
	1, // 0: COMM_AlgoCenter.AlgoCenterResponse.item_list:type_name -> COMM_AlgoCenter.ItemData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_AlgoCenter_proto_init() }
func file_AlgoCenter_proto_init() {
	if File_AlgoCenter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_AlgoCenter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlgoCenterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AlgoCenter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AlgoCenter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlgoCenterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AlgoCenter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AlgoCenter_proto_goTypes,
		DependencyIndexes: file_AlgoCenter_proto_depIdxs,
		MessageInfos:      file_AlgoCenter_proto_msgTypes,
	}.Build()
	File_AlgoCenter_proto = out.File
	file_AlgoCenter_proto_rawDesc = nil
	file_AlgoCenter_proto_goTypes = nil
	file_AlgoCenter_proto_depIdxs = nil
}
